### ISSUE TITLE
get title after leftButton

### ISSUE THREAD

**Issue by chirag04** [Kureev/react-native-navbar#16] opened 2015-04-15 16:21 UTC
If you try to add customTitle it will be rendered before the left Button.

After looking at the source it seems like you get the title first and then the left button.

Check: https://github.com/Kureev/react-native-navbar/blob/master/index.js#L199-L200

Not sure if this is a bug or i'm doing something wrong. I can send a PR if you think this is a bug.

**Comment by Kureev** [comment] 2015-04-15 17:01
Nope, it's not a bug. Now it works like this: you have a full-wide stretched title, which is placed underneath buttons (by using `position: absolute`). It's done this way, because of flex box model doesn't work good for this case. If you have any problems with positioning, just let me know and put some code here, I'll help you figure out how to do your case the best way.

**Comment by chirag04** [comment] 2015-04-15 17:31
I'm trying to center the image in this gist of yours: https://gist.githubusercontent.com/Kureev/929f351064b63f8170e0/raw/fedf021b0747f7d196ee38567c7cd381129e7782/example.js

I think only title is stretched. customTitle is not stretched using ``position: absolute`` 
https://github.com/Kureev/react-native-navbar/blob/master/index.js#L133-L134

**Comment by chirag04** [comment] 2015-04-15 17:32
This is how it looks now:


![ios simulator screen shot apr 15 2015 1 31 26 pm](https://cloud.githubusercontent.com/assets/954063/7165154/bfe51620-e373-11e4-9f30-cc72db74bcc9.png)

**Comment by Kureev** [comment] 2015-04-15 17:32
Wow, looks like a bug, gonna fix it ASAP

**Comment by chirag04** [comment] 2015-04-15 17:46
sweet! Glad i could help.

**Comment by chirag04** [comment] 2015-04-15 20:31
I can get your image example to work if i add below style to the view in customTitle:

```
navbar: {
    alignItems: 'center',
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: 320, //replace with screenWidth.
    paddingVertical: 5,
  }
```

```
var CustomTitle = React.createClass({
  render: function() {
    return (
      <View style={styles.navbar}>
        <Image source={{uri}} style={{ width: 32, height: 32 }} />
      </View>
    );
  }
});
```

**Comment by Kureev** [comment] 2015-04-15 20:32
I'm doing exactly the same, but in library: I'll wrap all custom titles with View with those css. Fix will be there soon

**Comment by chirag04** [comment] 2015-04-15 20:33
That would be ideal solution. Looking forwards. Appreciate your efforts.

**Comment by Kureev** [comment] 2015-04-15 21:53
Fixed in 0.4.3

**Comment by chirag04** [comment] 2015-04-16 16:15
@Kureev Awesome!

One problem is the customTitle is not vertically centered like the prev button.. marginTop of 30 on customTitle will not let the image to align with prev button if the image is more than 32x32. Does that make sense?

**Comment by chirag04** [comment] 2015-04-16 16:22
So instead of marginTop: 30 on customTitle, it should be bottom: 5 to align with prev and next buttons.

**Comment by Kureev** [comment] 2015-04-16 17:14
The idea is that custom components totally on your own. It means that positioning, alignment etc you should do by hands. There's no reason to add any style for those components by default, anyway it's gonna be customized :). I don't wanna confuse anybody with any unexpected styles.

**Comment by chirag04** [comment] 2015-04-16 17:36
I understand. 

All i'm saying is marginTop of 30 will give you height of 32 for your customTitle. Beyond that it will be cut off. Also, there is no way one can align customTitle with back button on that height of 32.

Back button is center aligned using flex-end with a paddingBottom of 5. CustomTitle should either be aligned with the bottom of back button or top of the backbutton. marginTop of 15/16 or bottom:0 would do that. 

I can give you an example to elaborate more.

**Comment by Kureev** [comment] 2015-04-16 18:32
Hm, not sure I got it: in the examples I've set `bottom: 5` and `left/right: 5` manually, it's not included in the component. I admit, that `marginTop` wasn't the best solution, but it's usage on your own, isn't it? Please, let me know if I missed something.

**Comment by chirag04** [comment] 2015-04-16 19:02
example contains next and prev buttons which are not wrapped in a view which is positioned absolutely. That is why you can do all that custom position in prev/next button.

Since customTitle is wrapped in a view which is positioned absolutely , I cannot set the bottom etc. Even if i set bottom it will be within this view and not relative to the navbarContainer.

Solution here is bottom: 5 to customTitle for two things:
1) navbarContainer has a paddingBottom of 5. customTitle needs that too to be able to align with other components.
2) customTitle is wrapped in a view with absolute position unlike other components. bottom will ensure it is aligned with navbarContainer.

**Comment by Kureev** [comment] 2015-04-16 19:43
Okay, do you wanna to make a PR?

**Comment by Kureev** [comment] 2015-04-16 20:15
@chirag04 agree?

**Comment by chirag04** [comment] 2015-04-16 20:27
LGTM. Can you bump the version?

**Comment by Kureev** [comment] 2015-04-16 20:28
Sure, in a sec!

**Closed** 2015-04-16 20:30 UTC

**Comment by chirag04** [comment] 2015-04-16 20:32
w00t! 

Just tried it with the new version. It's perfect. Thanks for working on this one.

**Comment by Kureev** [comment] 2015-04-16 20:33
@chirag04 thanks for your contribution to project. You helped a lot!

**Comment by chirag04** [comment] 2015-04-16 20:34
sure. thanks to you too for this awesome module.
